spring:
  application:
    name: scheduler

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: public

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

springdoc:
  swagger-ui:
    persistAuthorization: true
    tags-sorter: alpha
    operations-sorter: method

logging:
  level:
    root=WARN:
#  file:
#    name: scheduler_log.log

application:
  security:
    jwt:
      # Generate a key HMCA SHA-256 https://www.freeformatter.com/hmac-generator.html
      secret-key: ${JWT_SECRET_KEY}
      # Expiration time in  milliseconds
      expiration: ${JWT_EXPIRATION}

      refresh-token:
        # Expiration time in  milliseconds
        expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

resilience4j:
  retry:
    instances:
      rabbitmq-retry:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - org.springframework.amqp.AmqpException
          - java.net.ConnectException

#Bucket4j
rate-limit:
  authenticated:
    capacity: 5
    refill-tokens: 5
    refill-duration-minutes: 1
  pub:
    capacity: 5
    refill-tokens: 5
    refill-duration-minutes: 1